### ISSUE TITLE
# 功能建议

### ISSUE THREAD

**Issue by hotwa** [wukongdaily/diy-nas-onescript#1]
根分区比较小是否在脚本可以扩充根分区，[参考](https://www.bilibili.com/video/BV1SB4y1J7HP)

**Comment by wukongdaily** [comment]
你好，看到你的功能需求。分2个情况，若安装的时候用户没有勾选 “使用LVM逻辑卷”，那么在本机系统。无论用命令行还是用带界面的磁盘管理工具。都无法实现调整根目录大小的功能，只能借助另外的系统，比如live usb启动另一个系统，在另一个系统下去调整分区。若安装的时候用户勾选了【使用lvm逻辑卷】那么，命令行和带界面的磁盘工具都可以轻松调整。
