### ISSUE TITLE
visual box 自启动未生效

### ISSUE THREAD

**Issue by fanzai0403** [wukongdaily/diy-nas-onescript#4]
整个系统是按照你的教程装的。但是配置的OpenWrt虚拟机自启动无效。
如何查下原因？哪里有日志吗？

**Comment by wukongdaily** [comment]
请问现在什么情况了。然后当时openwrt 手动启动的时候是否启动成功。另外查看一下这个文件 是否有代码

`cat /etc/rc.local`

**Comment by fanzai0403** [comment]
fan@mini-box:~$ cat /etc/rc.local
#!/bin/sh -e
sleep 5
su - fan -c "VBoxHeadless -s OpenWrt &"
exit 0


执行：`su - fan -c "VBoxHeadless -s OpenWrt &"`，或是手动启动OpenWrt，都可以正常启动

**Comment by fanzai0403** [comment]
又试了一次，这次好了。原来是启动太慢了。大概用户登录完成后，一分多钟才开始启动OpenWrt。不知道什么原因，可能我的3865u比较慢~~

悟空，有没有微信或者群啥的？我加进去平时很多问题想请教~
