### ISSUE TITLE
一键脚本的选项6(img2vdi)运行失败，报错：VERR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by 532763233** [wukongdaily/diy-nas-onescript#7]
运行选项6(img2vdi)时先报找不到软件包pv
![3f8fd1a92b1d0e22a44ca58ea3a0341](https://github.com/wukongdaily/diy-nas-onescript/assets/62412476/7bd49c5e-b880-4c1b-bf3c-ceae97d8f7da)
在更换为上海交大源后依旧提示找不到pv包
而后转换未解压的img文件时报错：VBoxManage: error: cannot create the disk image "/home/****/Downloads/istoreos-22.03.5-2023112413-x86-64-squashfs-combined.img.vdi": VERR_INVALID_PARAMETER
而解压后的img文件是可以转换成功的，初步判断是在解压文件是嵌套了pv包展示进度但因为下载pv包失败从而导致转换报错
![78e7fa520e9a4bf7962ed21e50b5c52](https://github.com/wukongdaily/diy-nas-onescript/assets/62412476/835253e9-9b21-4813-972b-0219f777ddf4)

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/diy-nas-onescript/commit/c9be3c2a611e8f6edd759cd4d74a2f2e3211df48
已解决。
